[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  let g:gruvbox_italic = 1
  let g:gruvbox_invert_selection = 0
  let g:gruvbox_contrast_dark = 'hard'
  colorscheme gruvbox
  set background=dark
'''

[[plugins]]
repo = 'vim-scripts/pacmanlog.vim'
hook_add = '''
  autocmd BufRead pacman.log setfiletype pacmanlog
'''

[[plugins]]
repo = 'vim-scripts/rtorrent-syntax-file'
