[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'whatyouhide/vim-gotham'
hook_add = 'color gotham'

[[plugins]]
repo = 'vim-scripts/pacmanlog.vim'
hook_add = 'autocmd BufRead pacman.log setfiletype pacmanlog'
